// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../entities/todo.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7079696041178703992),
      name: 'ToDo',
      lastPropertyId: const IdUid(3, 5001949980353431286),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 208758675356234116),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6043952879399973092),
            name: 'task',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5001949980353431286),
            name: 'done',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7079696041178703992),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ToDo: EntityDefinition<ToDo>(
        model: _entities[0],
        toOneRelations: (ToDo object) => [],
        toManyRelations: (ToDo object) => {},
        getId: (ToDo object) => object.id,
        setId: (ToDo object, int id) {
          object.id = id;
        },
        objectToFB: (ToDo object, fb.Builder fbb) {
          final taskOffset = fbb.writeString(object.task);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, taskOffset);
          fbb.addBool(2, object.done);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ToDo(
              task: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              done:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ToDo] entity fields to define ObjectBox queries.
class ToDo_ {
  /// see [ToDo.id]
  static final id = QueryIntegerProperty<ToDo>(_entities[0].properties[0]);

  /// see [ToDo.task]
  static final task = QueryStringProperty<ToDo>(_entities[0].properties[1]);

  /// see [ToDo.done]
  static final done = QueryBooleanProperty<ToDo>(_entities[0].properties[2]);
}
